### ISSUE TITLE
box-sizing: border-box

### ISSUE THREAD

**Issue by mwendell** [tsvensen/equalize.js#3]
There appears to be a problem applying equalize.js to elements which use the **border-box** box-sizing model. The newly computed sizes do not seem to account for the padding.

Not sure if this is something that can be incorporated into the plugin. I may simply have to revert those elements back to the **content-box** sizing model.

Nevertheless, it's a fantastic plugin. Now if you could just make it so that the contents are vertically centered within the boxes, I'd be in heaven (kidding... or... well... seriously though, that would be super awesome... like, "tell me where to send the check" awesome.).

_Thanks!_

**Comment by mwendell** [comment]
My bad... using the **outerHeight** dimension method seems to handle border-box just fine. Sorry about that.

**Comment by tsvensen** [comment]
mwendell, that's exactly why I implemented equalize to accept all the jQuery methods. I should update the documentation and demo page to explicitly call that out.  Thanks.

I actually have another plugin (work-in-progress, not on github yet) that has centering part of the solution. There are a few CSS approaches.  I personally like:

``` css
.parent { position: relative; }

.element {
  position: absolute;
  top: 50%;
  left: 50%;
  margin: "minus half the elements height"px 0 0 "minus half the elements width"px
}
```

This is saying, relatively from the parent, position the element half of the parent's height and width, then pull the element up and to the left half the element's height and width.

Hopefully that helps, be on the look out for that new plugin release.
